container:
  image: xeffyr/termux-advanced-builder:latest
  cpu: 8
  memory: 16

# Build packages.
build_task:
  # 2 hours is a maximal timeout for free use.
  timeout_in: 120m

  environment:
    matrix:
      TERMUX_ARCH: aarch64
      TERMUX_ARCH: arm
      TERMUX_ARCH: i686
      TERMUX_ARCH: x86_64

  # Determine changes in repository and build modified packages.
  build_script: |
    sudo service ssh start
    mkdir -p "$HOME/.ssh"
    # Maintainer's (@xeffyr) SSH public key.
    echo "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIH5jsA0CQfw+um7V7BGxERRKQSnKM8B1Wl33zieAu7/z" > "$HOME/.ssh/authorized_keys"
    # Allow to stop debug shell on exit.
    echo "kill \$(pgrep -f \"ssh -R \${CIRRUS_TASK_ID}\") &" > "$HOME/.shutdown_script"
    echo "nohup bash \${HOME}/.shutdown_script > /dev/null 2>&1" > "$HOME/.bash_logout"
    # Reverse SSH via Serveo.net.
    # Connect with: ssh -J serveo.net builder@${CIRRUS_TASK_ID}
    ssh -R "${CIRRUS_TASK_ID}:22:localhost:22" serveo.net || true
